"use client";
import Footer from "./components/common/footer/Footer";
import Navbar from "./components/common/navbar/Navbar";
import "./globals.css";
// import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gradient-linear`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
